name: test-ci

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Setup node.js (version: LTS)'
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run test-ci
      - name: Send to coveralls
        uses: coverallsapp/github-action@1.1.3
        env:
          NODE_COVERALLS_DEBUG: '1'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

